[package]
name = "crust-mantle-adapter"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
experimental-audio-worker = []

[dependencies]
base64.workspace = true
crust = { path = "../crust" }
mantle-audio = { git = "https://github.com/rayan6ms/mantle", rev = "edc7fb1" }
mantle-core = { git = "https://github.com/rayan6ms/mantle", rev = "edc7fb1" }
mantle-media = { git = "https://github.com/rayan6ms/mantle", rev = "edc7fb1" }
serde_json.workspace = true
microfft = { version = "0.6.0", default-features = false, features = ["size-1024"] }
micromath = "2.1.0"
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
crust-testkit = { path = "../crust-testkit" }
