[package]
name = "crust-oto-adapter"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
crust = { path = "../crust" }
futures-util.workspace = true
oto = { git = "https://github.com/rayan6ms/oto", rev = "8fd22802cba9623164292fe2ecbdefba0f414487" }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
oto = { git = "https://github.com/rayan6ms/oto", rev = "8fd22802cba9623164292fe2ecbdefba0f414487", features = ["testkit"] }
oto-testkit = { git = "https://github.com/rayan6ms/oto", rev = "8fd22802cba9623164292fe2ecbdefba0f414487" }
serde_json.workspace = true
stats_alloc = "0.1.10"
