[package]
name = "crust-oto-adapter"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
crust = { path = "../crust" }
futures-util.workspace = true
oto = { git = "https://github.com/rayan6ms/oto", rev = "efa16faa8a3bd472f0818f65bd89f745f6b97f6d" }
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
oto = { git = "https://github.com/rayan6ms/oto", rev = "efa16faa8a3bd472f0818f65bd89f745f6b97f6d", features = ["testkit"] }
oto-testkit = { git = "https://github.com/rayan6ms/oto", rev = "efa16faa8a3bd472f0818f65bd89f745f6b97f6d" }
serde_json.workspace = true
stats_alloc = "0.1.10"
