[package]
name = "crust-oto-adapter"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
crust = { path = "../crust" }
futures-util.workspace = true
oto = { git = "https://github.com/rayan6ms/oto", rev = "4f68e8c7bf17c76c3cf7d6b5467c437fb304fe85" }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
oto = { git = "https://github.com/rayan6ms/oto", rev = "4f68e8c7bf17c76c3cf7d6b5467c437fb304fe85", features = ["testkit"] }
oto-testkit = { git = "https://github.com/rayan6ms/oto", rev = "4f68e8c7bf17c76c3cf7d6b5467c437fb304fe85" }
serde_json.workspace = true
stats_alloc = "0.1.10"
